---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: LetsEncrypt
    pipeline_stages:
      - match:
          selector: '{filename=~".*php/error.log"}'
          stages:
            - regex:
                expression: "\\[(?P<time>\\d{2}-[A-Z][a-z]{2,7}-\\d{4} \\d{2}:\\d{2}:\\d{2})\\] (?P<level>\\w{3,8})"
            - timestamp:
                source: time
                format: "02-Jan-2006 15:04:05"
            - labels:
                level:
      - match:
          selector: '{filename=~".*fail2ban/fail2ban.log"}'
          stages:
            - regex:
                expression:
                  "(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2},\\d{0,3})?\\D?
                  (?P<message>fail2ban.*(?P<pid>\\[\\d*\\]: )(?P<level>[A-Z]{4,7}) .*
                  (?:(?:\\[|Jail ')(?P<jail>\\D*)(?:\\]|'))?.*)"
            - template:
                source: message
                template: '{{ Replace .Value .pid "" -1 }}'
            - regex:
                expression: '(?P<message>.*)(?: - \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
                source: message
            - regex:
                expression: '(?P<message>.*)(?:\.\d{1,3}\.\d{1,3}$)'
                source: message
            - template:
                source: time
                template: '{{ Replace .Value "," "." -1 }}'
            - timestamp:
                source: time
                format: "2006-01-02 15:04:05.000"
            - output:
                source: message
      - match:
          selector: '{filename=~".*nginx/access.log"} |~ "/api/datasources/proxy/8/loki"'
          action: drop
      - match:
          selector: '{filename=~".*nginx/access.log"}'
          stages:
            - regex:
                expression: '- \[(?P<time>\d{2}/[A-Z][a-z]{2,7}/\d{4}:\d{2}:\d{2}:\d{2} [+-]\d{4})\] ".*HTTP/(?:1\.1|2+.0)" (?P<level>\d{3})'
            - timestamp:
                source: time
                format: "02/Jan/2006:15:04:05 -0700"
            - replace:
                expression: '(1\d\d)'
                source: "level"
                replace: "INFO"
            - replace:
                expression: '(2\d\d)'
                source: "level"
                replace: "INFO"
            - replace:
                expression: '(3\d\d)'
                source: "level"
                replace: "NOTICE"
            - replace:
                expression: '(4\d\d)'
                source: "level"
                replace: "WARN"
            - replace:
                expression: '(5\d\d)'
                source: "level"
                replace: "WARN"
            - labels:
                level:
      - match:
          selector: '{filename=~".*nginx/error.log"}'
          stages:
            - regex:
                expression: '(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w{3,8})\]'
            - timestamp:
                source: time
                format: "2006/01/02 15:04:05"
            - template:
                source: level
                template: "{{ ToUpper .Value }}"
            - labels:
                level:

    static_configs:
      - targets:
          - unraid
        labels:
          job: LetsEncrypt
          __path__: /_logs/LE/**/*.log
